version: 2

models:
  - name: stg_vtiger_visitescf
    description: "Table de staging des visites"
    columns:
      - name: visitesid
        tests: [not_null, unique]

  - name: stg_vtiger_succursalescf
    description: "Table de staging des succursales"
    columns:
      - name: succursaleid
        tests: [not_null, unique]

  - name: stg_vtiger_accessoirescf
    description: "Table de staging des accessoires"
    columns:
      - name: accessoireid
        tests: [not_null, unique]

  - name: stg_vtiger_objectifsuccursalecf
    description: "Table de staging des objectifs succursales"
    columns:
      - name: objectifsuccursaleid
        tests: [not_null, unique]

  - name: stg_vtiger_salesordercf
    description: "Table de staging des bons de commande"
    columns:
      - name: salesorderid
        tests: [not_null, unique]

  - name: stg_vtiger_accountscf
    description: "Table de staging des comptes"
    columns:
      - name: accountid
        tests: [not_null, unique]
  
  - name: stg_vtiger_objectifvmcf
    description: "Table de staging des objectifs"
    columns:
      - name: objectifvmcf
        tests: [not_null, unique]

  - name: stg_vtiger_account
    description: "Table 2 de staging des comptes"
    columns:
      - name: accountid
        tests: [not_null, unique]

  - name: stg_vtiger_cf_2801
    description: "Table de staging du canal"
    columns:
      - name: cf_2801id
        tests: [not_null, unique]

  - name: stg_vtiger_cf_1977
    description: "Table de staging du region"
    columns:
      - name: cf_1977id
        tests: [not_null, unique]

  - name: stg_vtiger_cf_1361
    description: "Table de staging du statut"
    columns:
      - name: cf_1361id
        tests: [not_null, unique]

  - name: stg_vtiger_cf_2777
    description: "Table de staging du reseau"
    columns:
      - name: cf_2777id
        tests: [not_null, unique]

  - name: stg_vtiger_cf_2647
    description: "Table de staging du marque"
    columns:
      - name: cf_2647id
        tests: [not_null, unique]


