version: 2

sources:
  - name: raw_data
    database: AIRBYTE_DATABASE_AUDI    
    schema: EPEGAFIDECONSULT_DB                 
    tables:
      - name: vtiger_ventescf
      - name: vtiger_visitescf
      - name: vtiger_succursalescf
      - name: vtiger_accessoirescf
      - name: vtiger_objectifsuccursalecf 
      - name: vtiger_salesordercf
      - name: vtiger_field
      - name: vtiger_accountscf
      - name: vtiger_objectifvmcf
      - name: vtiger_account
      - name: vtiger_cf_2801
      - name: vtiger_cf_1977
      - name: vtiger_cf_1361
      - name: vtiger_cf_2777
      - name: vtiger_cf_2647
      - name: vtiger_cf_1823  
      - name: vtiger_objectifaudiocf  
      - name: vtiger_objectifcrccf
      - name: vtiger_contactscf 
      - name: vtiger_leadscf
