version: 2

sources:
  - name: raw_data
    database: AIRBYTE_DATABASE_AUDI    
    schema: EPEGAFIDECONSULT_DB                 
    tables:
      - name: vtiger_ventescf
      - name: vtiger_visitescf
      - name: vtiger_succursalescf
      - name: vtiger_accessoirescf
      - name: vtiger_objectifsuccursalecf 
      - name: vtiger_salesordercf
      - name: vtiger_field
      - name: vtiger_accountscf
      - name: vtiger_objectifvmcf
      - name: vtiger_account
